"""add aws_accounts table

Revision ID: 8411fce00a25
Revises: 
Create Date: 2026-10-07 21:48:40.645084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8411fce00a25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aws_accounts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('aws_account_id', sa.String(), nullable=False),
    sa.Column('role_arn', sa.String(), nullable=False),
    sa.Column('external_id', sa.String(), nullable=True),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aws_accounts')
    # ### end Alembic commands ###
