"""add audit leads table

Revision ID: 95b5b1fbe257
Revises: 47551907b7bb
Create Date: 2026-10-09 19:26:31.909285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '95b5b1fbe257'
down_revision: Union[str, None] = '47551907b7bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=False),
    sa.Column('work_email', sa.String(), nullable=False),
    sa.Column('monthly_spend_range', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_leads_work_email'), 'audit_leads', ['work_email'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_leads_work_email'), table_name='audit_leads')
    op.drop_table('audit_leads')
    # ### end Alembic commands ###
